version: '3'

services:
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8082:80"
  nginx:
    image: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - php
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
        PMA_HOST: db
    ports:
        - 8000:80
    depends_on:
        - db