version: "3.8"
services:
  php:
    container_name: php_apache
    build: src
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./src/init.sql:/docker-entrypoint-initdb.d/init.sql"
